# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Bump version and create tag
      id: tag
      uses: mathops/git-tag-action@v1
      with:
        tag_prefix: 'v'
        # or you can compute a new tag number here
        # tag: 'v1.0.${{github.run_number}}'

    - name: Push tag
      uses: ad-m/github-push-action@v0.1.0
      with:
        tag: ${{steps.tag.outputs.new_tag}}

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
